### ISSUE TITLE
create variable simulation_df to read json from frontend

### ISSUE THREAD

**Issue by dunland** [quarree100/qScope_infoscreen#2]
The simulation mode in the frontend creates a file `simulation_df.json` which shall be used in the infoscreen but I have trouble implementing a variable `simulation_df` in the infoscreen properly.
Right now, the variable is loaded in `index.html` and declared **inside the json file** which should definetely not be done this way!

We need something like:
``` javascript
const simulation_df = require('fs').readFileSync("public/data/simulation_df.json", 'utf8');
var jsonData = JSON.parse(simulation_df);
console.log(jsonData);
```

Problems:
- the `require` module can only be loaded in the node.js main file `q100_info.js`
- if `simulation_df` is declared in the main file, it cannot be accessed in `viz.js` and `main.js`

**→ How do we properly declare `simulation_df` in the project to have it globall accesible?**

Hint: maybe we will have to restructure the whole project, according to this outline:
https://softwareontheroad.com/ideal-nodejs-project-structure/

@kazux2 please try to declare `simulation_df` in a better way. If restructuring the whole project is necessary, start a new branch and keep me updated!

**Comment by kazux2** [comment]
Hi David, I did a little research and it seemed hard to declare variable which are accessible to the server-side js (node express js) and static js (main.js). (I'm not so sure, but it might be possible if these static js are generated by express).

Meanwhile, I found a reference that implements D3.js with express, and in this, static js fetches data from node js server via HTTP endpoint, and I implemented it in the same way. There is no restructuring but it works with normal json format(without declaring the variable inside the json file). What do you think?
