### ISSUE TITLE
questionnaire view

### ISSUE THREAD

**Issue by dunland** [quarree100/qScope_infoscreen#6]
As briefly outlined in [here](https://github.com/quarree100/qScope_frontend/issues/25#issuecomment-1061599492), there is a preliminary questionnaire mode preceding the general input mode. We will need a simple layout like this:

![infoscreen-mockup_mindsetQuestions_2022-03-08](https://user-images.githubusercontent.com/23742320/157211352-575c394d-2e0f-4892-8d49-f56fb9814fe9.png)

As example questions, we can take these:
> - "Die globale Erderwärmung wird durch von Menschen produzierte Emissionen verstärkt."
> - "Der Schutz der Umwelt ist ein Mittel zur Stärkung des Wirtschaftswachstums in Deutschland." 
> - "Ich glaube, dass wir jedes Mal, wenn wir Kohle, Öl oder Gas verwenden, zum Klimawandel beitragen."
> - "Ich würde meinen Energieverbrauch reduzieren, wenn mein Haushalt mehr Energie verbraucht als ähnliche Haushalte."
> - "Wenn ein erneuerbarer Energietarif bei einem anderen Energieversorger verfügbar wäre, würde ich meinen Anbieter wechseln."

each to be answered with yes or no. Each answer directly leads to the next question, and the last question eventually starts the general input mode.

### open questions
- should each user approach the questionnaire alone, meaning one after the other?
- instead, a collective decision mode could be worked out using the table with large interfaces "YES" and "NO" and require all users to place their **individual token** simultaneously (are there enough IDs for this? How precise is the token detection?)

**Comment by kazux2** [comment]
I pushed some commits on data-view branch (work in progress).

(Status)
Now, the questionnaire view shows the default 6 questions randomly.
Todo: Change with socket message is implemented but not tested with socket messaging

**Comment by dunland** [comment]
Great! I just tested switching the modes via frontend. It works!
Some more **TODOs**:
- [ ] when re-entering the questionnaire-mode, there is an Error messsage "the question was not provided". The case of re-entering this mode will only appear during debugging, but nevertheless it would be helpful to have it show up. Please take care, that a question is provided in this case ;)
- [ ] show a green/red field saying YES/NO like in the example. The areas will be selectable via slider and should be highlighted acording to where the slider is at. The frontend will provide a string "answer": "yes" or "answer": "no". Please highlight the according area, maybe using a thicker stroke weight.
- [ ] do some layouting (centering text, pick a nice font, maybe something with serifs and in italics..)

**Comment by kazux2** [comment]
![image](https://user-images.githubusercontent.com/29823397/158283218-0384e0f9-d514-4a42-b3ce-612a653b11ff.png)
hi David, I created the questionnaire (single user mode) as above. I haven't tested with socket messaging yet, but the function is implemented. 
I couldn't recreate the bug you mentioned as the first todo. Do you mean when you hit the space bar to toggle the view, the question becomes "the question was not provided" after the second time? If so, it doesn't happen in my environment.

**Comment by dunland** [comment]
socket communication works perfectly!
..except that after some playing around, it always says "question not provided" ‒ switching the modes via space bar works fine and even reloads the question, but using the socket communication it does not. Is there a difference between the two ways of switching?

I though it would be a good idea to transmit a message containing "question_number" to access the specific questions one after the other.
```
{"year": 0, "foerderung": 0, "CO2-Preis": 0, "connection_speedCO2-emissions": 0, "versorgung": 0, "investment": 0, "anschluss": 0, "answer": "yes", "mode": "questionnaire", "question_number": 0}
```

**Comment by dunland** [comment]
The questions are now sent to the infoscreen via socket message directly.
e.g. `"question": "Die globale Erderwärmung wird durch von Menschen produzierte Emissionen verstärkt."`

**Comment by kazux2** [comment]
all implemented in data-view branch
